### ISSUE TITLE
fortnite detected

### ISSUE THREAD

**Issue by skullcheat** [understatements/Fortnite-Neural-Network-Cheat#1]
hello thank you very much for sharing my fortnite detects that you are using third-party software

**Comment by skullcheat** [comment]
and would you like to put it undetectable then resell it? if yes add me on discord skullcheat#2183
Thanks to the pleasure and great menu!

**Comment by understatements** [comment]
the cheat is not detected.
since this is open-source software, we added a license to prohibit selling of this software.
